# KEYBINDINGS

## Bind flags

# bind supports flags in this format:
# bind[flags] = ...
# e.g.:
# bindrl = MOD, KEY, exec, amongus

## Flags:

# l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
# r -> release, will trigger on release of a key.
# c -> click, will trigger on release of a key or button as long as the mouse cursor stays inside binds:drag_threshold.
# g -> drag, will trigger on release of a key or button as long as the mouse cursor moves outside binds:drag_threshold.
# o -> longPress, will trigger on long press of a key.
# e -> repeat, will repeat when held.
# n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
# m -> mouse, see below.
# t -> transparent, cannot be shadowed by other binds.
# i -> ignore mods, will ignore modifiers.
# s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
# d -> has description, will allow you to write a description for your bind.
# p -> bypasses the app's requests to inhibit keybinds.

# Example Usage:

# # Example volume button that allows press and hold, volume limited to 150%
# binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+

# # Example volume button that will activate even while an input inhibitor is active
# bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# # Start wofi opens wofi on first press, closes it on second
# bindr = SUPER, SUPER_L, exec, pkill wofi || wofi

# # Describe a bind
# To add a description to a keybind, use:
# bindd = MOD, KEY, Description, action, [args]
# Example: 
# bindd = SUPER, Q, Kill active window (SUPER+Q), killactive,
# bindd = SUPER, return, Open my favourite terminal (Super+Enter), exec, kitty

# # Skip player on long press and only skip 5s on normal press
# bindo = SUPER, XF86AudioNext, exec, playerctl next
# bind = SUPER, XF86AudioNext, exec, playerctl position +5

# --- Main modifier ---
$mainMod = SUPER

# source = ~/.config/hypr/bindings/unbind.conf
source = ~/.config/hypr/bindings/window.conf
source = ~/.config/hypr/bindings/workspace.conf
source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/apps.conf
source = ~/.config/hypr/bindings/system.conf



