-- Display configuration is generated by nwg-displays.
-- See https://github.com/nwg-piotr/nwg-displays#hyprland
--
-- Hyprland 0.55+ uses ~/.config/hypr/monitors.lua. nwg-displays writes that
-- file alongside monitors.conf whenever display settings are applied.
-- monitors.lua is intentionally not tracked by this repository.

local ok, err = pcall(require, "monitors")

if not ok then
  -- Keep the session usable before nwg-displays has generated monitors.lua.
  -- Applying a layout in nwg-displays will write monitors.lua and reload
  -- Hyprland, replacing this fallback immediately.
  print("Could not load nwg-displays monitors.lua: " .. tostring(err))

  hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
  })
end
