# https://wiki.hyprland.org/Configuring/

# Modular config include files - The order matters...
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/workspaces.conf
