# See https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock                  # start the lock screen if it is not already running
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # avoid pressing a key twice to turn on the display
    inhibit_sleep = 3                                      # wait until screen is locked
}

#listener {
#    timeout = 150                                             # 2.5min
#    on-timeout = pidof hyprlock || hyprlock                   # start lock screen if we have not locked already
#}

listener {
    timeout = 151                      # about 2.5min
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r # screen on when activity is detected
}
