-- Legacy source: Generated by nwg-displays on 2026-05-06 at 14:57:50. Do not edit manually.
-- Ported from the generated monitors.conf layout.
-- This file is now the source of truth for the Lua branch.

hl.monitor({
  output = "eDP-1",
  mode = "2256x1504@60.0",
  position = "1560x1080",
  scale = 1.57,
})

hl.monitor({
  output = "DP-5",
  mode = "1920x1080@60.0",
  position = "1560x0",
  scale = 1.0,
})

hl.monitor({
  output = "DP-6",
  mode = "1920x1080@60.0",
  position = "3480x0",
  scale = 1.0,
})

hl.monitor({
  output = "DP-7",
  mode = "1920x1080@60.0",
  position = "5400x0",
  scale = 1.0,
})
