# WINDOWS AND WORKSPACES
# Workspace and window rules
# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
