# Application bindings
$terminal = ghostty #uwsm app -- $TERMINAL
$browser = librewolf #omarchy-launch-browser
$browser_private = librewolf --private-window
$browser_kiosk = --kiosk --new-window # could be web app alternative. currently launches fullscreen

$category = App:

# common apps
bindd = SUPER, return, $category Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, E, $category File manager, exec, uwsm app -- thunar # nautilus --new-window
bindd = SUPER, W, $category Browser, exec, $browser
bindd = SUPER SHIFT, W, $category Browser (private), exec, $browser_private
# bindd = SUPER, N, Editor, exec, omarchy-launch-editor

# other apps
# bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
# bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

$category = App Web:
# --- Web apps ---
# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, A, $category ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER, C, $category Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar" # "https://app.hey.com/calendar/weeks/"
# bindd = SUPER, E, $category Email, exec, omarchy-launch-webapp "https://mail.google.com/mail"#"https://app.hey.com"
bindd = SUPER, Y, $category YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
# bindd = SUPER SHIFT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER SHIFT, G, $category WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER ALT, G, $category Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER, X, $category X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT, X, $category X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"
bindd = SUPER, D, $category Canvas, exec,  omarchy-launch-webapp "https://isu.instructure.com/"
