$category = Media:
# --- Media and volume controls ---
# Use nerdfont symbols for special function keys descriptions
bindeld = ,XF86AudioRaiseVolume, $category Volume Up 󰕾, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindeld = ,XF86AudioLowerVolume, $category Volume Down , exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindeld = ,XF86AudioMute, $category Mute 󰖁, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindeld = ,XF86AudioMicMute, $category Mute Microphone 󰖁, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindld = ,XF86AudioNext, $category Next 󰒬, exec, playerctl next
bindld = ,XF86AudioPause, $category Pause 󰏤, exec, playerctl play-pause
bindld = ,XF86AudioPlay, $category Play 󰐊, exec, playerctl play-pause
bindld = ,XF86AudioPrev, $category Previous 󰒫, exec, playerctl previous

# Alternative bindings without description
# bindeld = ,XF86AudioRaiseVolume, ,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
# bindeld = ,XF86AudioLowerVolume, ,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
# bindeld = ,XF86AudioMute, ,  exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bindeld = ,XF86AudioMicMute, ,  exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# bindeld = ,XF86MonBrightnessUp, ,  exec, brightnessctl -e4 -n2 set 5%+
# bindeld = ,XF86MonBrightnessDown, ,  exec, brightnessctl -e4 -n2 set 5%-
# bindld = ,XF86AudioNext, ,  exec, playerctl next
# bindld = ,XF86AudioPause, ,  exec, playerctl play-pause
# bindld = ,XF86AudioPlay, ,  exec, playerctl play-pause
# bindld = ,XF86AudioPrev, ,  exec, playerctl previous