
$category = Tools: 
bindd = SUPER, T, $category System Monitor, exec, $terminal -e btop
bindrd = CTRL, ESCAPE, $category Toggle Waybar (CTRL+ESC), exec, pkill waybar || waybar
bindd = SUPER CTRL, I, $category Toggle lock on idle, exec, omarchy-toggle-idle
bindd = SUPER, PRINT, $category Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = CTRL SUPER, S, $category File Share, exec, omarchy-menu share

$category = Notifications:
bindd = SUPER, COMMA, $category Dismiss Last, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, $category Dismiss All, exec, makoctl dismiss --alL
bindd = SUPER CTRL, COMMA, $category Toggle Silence, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

$category = Menu:
bindd = ALT, SPACE, $category App Launcher, exec, walker -p "Start…"
bindd = SUPER CTRL, E, $category Emoji Picker, exec, walker -m Emojis
bindd = SUPER ALT, SPACE, $category Omarchy, exec, omarchy-menu
bindd = SUPER, ESCAPE, $category Power, exec, omarchy-menu system
bindld = , XF86PowerOff, $category Power, exec, omarchy-menu system
bindd = SUPER, K, $category Key Bindings, exec, ~/.config/hypr/scripts/omarchy-menu-keybindings

$category = Theme:
bindd = SUPER CTRL, SPACE, $category Next Background, exec, omarchy-theme-bg-next
bindd = SUPER SHIFT CTRL, SPACE, $category Pick, exec, omarchy-menu theme

$category = Display:
bindd = , PRINT, $category Screenshot of region, exec, omarchy-cmd-screenshot
bindd = SHIFT, PRINT, $category Screenshot of window, exec, omarchy-cmd-screenshot window
bindd = CTRL, PRINT, $category Screenshot of display, exec, omarchy-cmd-screenshot output

bindd = ALT, PRINT, $category Screen record a region, exec, omarchy-cmd-screenrecord region
bindd = ALT SHIFT, PRINT, $category Screen record a region with audio, exec, omarchy-cmd-screenrecord region audio
bindd = CTRL ALT, PRINT, $category Screen record display, exec, omarchy-cmd-screenrecord output
bindd = CTRL ALT SHIFT, PRINT, $category Screen record display with audio, exec, omarchy-cmd-screenrecord output audio

bindeld = ,XF86MonBrightnessUp, $category Brightness Up 󰌬, exec, brightnessctl -e4 -n2 set 5%+
bindeld = ,XF86MonBrightnessDown, $category Brightness Down 󰌭, exec, brightnessctl -e4 -n2 set 5%-

bindd = SUPER CTRL, N, $category Toggle nightlight, exec, omarchy-toggle-nightlight