# --- Unbinds & Overrides ---
# Unbind default or conflicting keys before setting new binds
unbind = SUPER, W
unbind = CTRL ALT, DELETE
unbind = SUPER, J
unbind = SUPER, P
unbind = SUPER, V
unbind = SHIFT, F11
unbind = ALT, F11
unbind = SUPER, left
unbind = SUPER, right
unbind = SUPER, up
unbind = SUPER, down
unbind = SUPER, code:10
unbind = SUPER, code:11
unbind = SUPER, code:12
unbind = SUPER, code:13
unbind = SUPER, code:14
unbind = SUPER, code:15
unbind = SUPER, code:16
unbind = SUPER, code:17
unbind = SUPER, code:18
unbind = SUPER, code:19
unbind = SUPER SHIFT, code:10
unbind = SUPER SHIFT, code:11
unbind = SUPER SHIFT, code:12
unbind = SUPER SHIFT, code:13
unbind = SUPER SHIFT, code:14
unbind = SUPER SHIFT, code:15
unbind = SUPER SHIFT, code:16
unbind = SUPER SHIFT, code:17
unbind = SUPER SHIFT, code:18
unbind = SUPER SHIFT, code:19
unbind = SUPER, TAB
unbind = SUPER SHIFT, TAB
unbind = SUPER CTRL, TAB
unbind = ALT, Tab
unbind = ALT SHIFT, Tab
unbind = ALT, Tab
unbind = ALT SHIFT, Tab
unbind = SUPER, code:20
unbind = SUPER, code:21
unbind = SUPER SHIFT, code:20
unbind = SUPER SHIFT, code:21
unbind = SUPER, mouse_down
unbind = SUPER, mouse_up
unbind = SUPER, mouse:272
unbind = SUPER, mouse:273

unbind = SUPER, K
unbind = , switch:on:Lid Switch
unbind = , switch:off:Lid Switch
unbind = SUPER, SPACE
unbind = Super, W
unbind = Super, Q
unbind = Super SHIFT, B
unbind = Super, B
unbind = Super, F
unbind = SUPER, F10
unbind = ALT, F10
unbind = Super, E
unbind = ALT, TAB