$category =  Window: 
# --- Window State ---
bindd = SUPER, SPACE, $category Toggle Floating, togglefloating
# see: https://wiki.hypr.land/Configuring/Dispatchers/#fullscreenstate
bindd = SUPER, F, $category Toggle Full Screen, fullscreen, 0
bindd = SUPER SHIFT, F, $category Toggle Maximize, Fullscreen, 1 
bindd = SUPER ALT, F, $category Toggle Full Screen Client (fake), fullscreenstate, -1 2

bindd = SUPER, Q, $category Close Active, killactive,

# --- Focus movement ---
bindd = $mainMod, left, $category Focus Left , movefocus, l
bindd = $mainMod, right, $category Focus Right , movefocus, r
bindd = $mainMod, up, $category Focus Up , movefocus, u
bindd = $mainMod, down, $category Focus Down , movefocus, d

# --- Mouse actions ---
bindmd = $mainMod, mouse:272, $category Mouse Move , movewindow
bindmd = $mainMod, mouse:273, $category Mouse Resize, resizewindow

bindd = SUPER, BACKSPACE, $category Toggle Transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
